# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0eda48bd0b67df3daeba6d19276c5c7329421fd78c4aa5c2fa86e71adec30ca897fe7b1ad40a5020fcb570ff86778cb42be8234c7f35fad5047146160d3397d

test:
  secret_key_base: c8d7c06bb4603177ad8f12031dc1c61a135b650555bcc93f06052df49e3df47290c4b7f47e0a9e7fbdaf7b98f1f2ed10f04828d8773a24831d177e94ae58aa6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
